[theme]
base = "dark"
primaryColor = "#6366F1"
backgroundColor = "#020617"
secondaryBackgroundColor = "#0F172A"
textColor = "#F8FAFC"
font = "sans serif"

[server]
maxUploadSize = 10
runOnSave = true

[browser]
gatherUsageStats = false
